### ISSUE TITLE
"Match Stats" in "Statistics" is blank

### ISSUE THREAD

**Issue by HighlyTrainedNeuralNetwork** [cderickson/MTGO-Tracker#24] opened 2023-09-01 18:22 UTC
When I open the "Match Stats" tab inside "Statistics" I see four empty quadrants and nothing else.
![image](https://github.com/cderickson/MTGO-Tracker/assets/56235713/cb0044ac-dde0-4dfe-816e-490b907bfec9)
As per https://cderickson.io/mtgo-tracker/ I am attaching a zip of my "DEBUG.txt".
[DEBUG.zip](https://github.com/cderickson/MTGO-Tracker/files/12500673/DEBUG.zip)

**Comment by cderickson** [comment] 2023-09-01 18:33
Do the other Statistics tabs load properly?

I'm unable to pinpoint the issue from the debug log, are you able to zip your /save folder so I can test on my machine?

**Comment by HighlyTrainedNeuralNetwork** [comment] 2023-09-01 18:39
Other tabs load with no issues yes. Attaching the save folder here:
[save.zip](https://github.com/cderickson/MTGO-Tracker/files/12500765/save.zip)

**Comment by cderickson** [comment] 2023-09-01 18:57
![Screenshot 2023-09-01 115055](https://github.com/cderickson/MTGO-Tracker/assets/17014141/28273519-4cbd-4b06-9046-2bf630e522b6)
The issue is that you only have 1 Match with Match_Type = 'Competitive Sealed'. Because this match is listed as 1-1 (one of the games is missing a Game_Winner), this is triggering a divide by zero error when computing Win% by Match_Type.

I've fixed the issue on my local machine and the fix will be included in the next update. To fix the error with the current MTGO-Tracker version you are using, you can either set the Game_Winner for that specific match manually, or set more matches with Match_Type = 'Competitive Sealed'.

Let me know if I didn't explain that clearly or you have other questions

**Comment by HighlyTrainedNeuralNetwork** [comment] 2023-09-01 19:13
Makes sense. Appreciate the quick support and in general this is an awesome tool. 
One thing I would like to mention in case it is ever relevant is that in addition to the game log files you are currently using MTGO uses Loupe (https://onloupe.com/) to generate .GLF logging files. Those are harder to work with since as far as I am aware you have to use Loupe to decode them but they contain far more information such as what cards are being drawn.

**Comment by cderickson** [comment] 2023-09-01 19:37
Interesting I'll have to look into that

**Closed** 2023-09-01 19:58 UTC
